routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function ()
{
    if (Auth::check()) {
        return redirect('home');
    }
    else {
        return redirect('login');
    }

})->name('index');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/login', 'Auth\LoginController@showLogin')->name('login');
Route::post('/login', 'Auth\LoginController@postLogin')->name('login');
Route::post('/logout', 'Auth\LoginController@logoutLogin')->name('logout');

Route::get('/productos/listar','ProductoController@list')->name('productos.listar');
Route::resource('/productos', 'ProductoController')->except([
    'create', 'edit', 'show'
]);

Route::get('/categories/list','CategoryController@list')->name('categories.list');
Route::resource('/categories', 'CategoryController')->except([
    'create', 'edit', 'show'
]);

Route::get('/clients/list','ClientController@list')->name('clients.list');
Route::resource('/clients', 'ClientController')->except([
    'create', 'edit', 'show'
]);

Route::get('/users/list','UserController@list')->name('users.list');
Route::resource('/users', 'UserController')->except([
    'create', 'edit', 'show'
]);

Route::get('/sales/ticket/{sale}','SaleController@ticket')->name('sales.ticket');
Route::get('/sales/list','SaleController@list')->name('sales.list');
Route::get('/sales/report','SaleController@report')->name('sales.report');
Route::get('/sales/getCliente','SaleController@getCliente')->name('sales.getCliente');
Route::resource('/sales', 'SaleController')->except([
    'create', 'edit', 'show'
]);

Route::get('/report/salesPerDay','ReportController@salesPerDay')->name('report.salesPerDay');
Route::get('/report/salesPerMonth','ReportController@salesPerMonth')->name('report.salesPerMonth');
Route::get('/report/clientsPerSex','ReportController@clientsPerSex')->name('report.clientsPerSex');

resources/views/categories.blade.php
@extends('layouts.app')

@section('title-tab', 'Categorias')
@section('title-page', 'Categorias')

@section('content')
    <categories-component title='Categoria' url-get="{{ route('categories.list') }}" url-create="{{ route('categories.store') }}" url-delete="{{ route('categories.destroy', '') }}" url-update="{{ route('categories.update', '') }}" gender-letter="a"></categories-component>
@endsection

resources/views/clients.blade.php
@extends('layouts.app')

@section('title-tab', 'Clientes')
@section('title-page', 'Clientes')

@section('content')
    <clients-component title='Cliente' url-get="{{ route('clients.list') }}" url-create="{{ route('clients.store') }}" url-delete="{{ route('clients.destroy','') }}" url-update="{{ route('clients.update','') }}" gender-letter="o"></clients-component>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('title-page', 'Inicio')
@section('title-tab', 'Inicio')

@section('content')
    <home-component></home-component>
@endsection

resources/views/products.blade.php
@extends('layouts.app')

@section('title-tab', 'Productos')
@section('title-page', 'Productos')

@section('content')
    <products-component title='Producto' url-get="{{ route('productos.listar') }}" url-create="{{ route('productos.store') }}" url-delete='productos/' url-update="productos/" gender-letter="o"></products-component>
@endsection

resources/views/sale_ticket.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Ticket de caja</title>
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

</head>
<body>
    <div class="container col-3">
        <h3 class="text-center">MojiDogs</h3>
        <p class="text-center"><strong>Numero: {{ $sale->numero }}</strong></p>
        <h5>Datos del cliente:</h5>
        <p class="mb-0">DNI: {{ $sale->cliente['dni']}} </p>
        <p class="mb-0">Nombres: {{ $sale->cliente['first_name']}} </p>
        <p class="mb-0">Apellidos: {{ $sale->cliente['last_name']}} </p>
        <p class="mb-0">Telefono: {{ $sale->cliente['phone']}} </p>
        <p class="mb-0">Dirección: {{ $sale->cliente['address']}} </p>
        <hr>
        <h5 class="mt-3">Detalles:</h5>

        <table class="table table-borderless table-sm mt-3">
            <thead>
            <tr>
                <th scope="col" class="text-center" width="15%">UND.</th>
                <th scope="col" class="text-center" width="45%">PRODUCTO</th>
                <th scope="col" class="text-center" width="20%">PRECIO</th>
                <th scope="col" class="text-center" width="20%">SUBTOTAL</th>
            </tr>
            </thead>
            <tbody>
                @foreach($sale->detalles as $detail)

                        <tr >
                            <th scope="row" class="text-center">{{ $detail['amount'] }}</th>
                            <td class="text-center">{{ $detail['product']['nombre'] }}</td>
                            <td class="text-center">{{ $detail['product']['precio'] }}</td>
                            <td class="text-center">{{ $detail['subtotal'] }}</td>
                        </tr>
                @endforeach
            </tbody>
        </table>
        <hr>
        <div class="row">
            <div class="col-6">
                <h3>TOTAL</h3>
            </div>
            <div class="col-6">
                <h3 class="text-right">{{ $sale->total }}</h3>
            </div>
        </div>
        <hr>
        <button class="btn btn-block btn-secondary" onclick="window.print()">Imprimir</button>
    </div>
</body>
</html>

resources/views/sales.blade.php
@extends('layouts.app')

@section('title-tab', 'Ventas')
@section('title-page', 'Generar Venta')

@section('content')
<sales-component title='Generar venta' numero="{{ $numero }}" url-cliente="{{ route('sales.getCliente') }}" url-create="{{ route('sales.store') }}" ticket-url="{{ route('sales.ticket', '') }}" gender-letter="a"></sales-component>
@endsection

resources/views/sales_report.blade.php
@extends('layouts.app')

@section('title-tab', 'Reporte de Ventas')
@section('title-page', 'Reporte de Ventas')

@section('content')
    <sales-report-component title='Reporte de Ventas' url-get="{{ route('sales.list') }}" gender-letter="o"></sales-report-component>
@endsection

resources/views/users.blade.php
@extends('layouts.app')

@section('title-tab', 'Usuarios')
@section('title-page', 'Usuarios')

@section('content')
    <users-component title='Usuario' url-get="{{ route('users.list') }}" url-create="{{ route('users.store') }}" url-delete="{{ route('users.destroy', '') }}" url-update="{{ route('users.update', '') }}" gender-letter="o"></users-component>
@endsection